# Generated by Django 5.1.1 on 2024-09-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_content_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='modul',
            new_name='module',
        ),
    ]
